import { PanchayatData } from "../types/nrega";

export function findPanchayatByCode(
  panchayatCode: string
): PanchayatData | undefined {
  return allData.find((data) => data.panchayat_code === panchayatCode);
}
export const allData: PanchayatData[] = [
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಫ್ಜಲ್‌ಪುರ",
    block_name_en: "AFZALPUR",
    block_code: "1515001",
    panchayat_name_kn: "ಅಳ್ಳೊಳ್ಳಿ",
    panchayat_name_en: "ALLAGI B",
    panchayat_code: "1515001003"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಫ್ಜಲ್‌ಪುರ",
    block_name_en: "AFZALPUR",
    block_code: "1515001",
    panchayat_name_kn: "ಆನೂರ",
    panchayat_name_en: "ANOOR",
    panchayat_code: "1515001014"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಫ್ಜಲ್‌ಪುರ",
    block_name_en: "AFZALPUR",
    block_code: "1515001",
    panchayat_name_kn: "ಆತನೂರ",
    panchayat_name_en: "ATNOOR",
    panchayat_code: "1515001022"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಫ್ಜಲ್‌ಪುರ",
    block_name_en: "AFZALPUR",
    block_code: "1515001",
    panchayat_name_kn: "ಬಡದಾಳ",
    panchayat_name_en: "BADADAL",
    panchayat_code: "1515001004"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಫ್ಜಲ್‌ಪುರ",
    block_name_en: "AFZALPUR",
    block_code: "1515001",
    panchayat_name_kn: "ಬಳೂರಗಿ",
    panchayat_name_en: "BALLURGI",
    panchayat_code: "1515001020"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಫ್ಜಲ್‌ಪುರ",
    block_name_en: "AFZALPUR",
    block_code: "1515001",
    panchayat_name_kn: "ಬಂದರವಾಡ",
    panchayat_name_en: "BANDARWAD",
    panchayat_code: "1515001021"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಫ್ಜಲ್‌ಪುರ",
    block_name_en: "AFZALPUR",
    block_code: "1515001",
    panchayat_name_kn: "ಬಂಕಲಗಾ",
    panchayat_name_en: "BANKALGA",
    panchayat_code: "1515001024"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಫ್ಜಲ್‌ಪುರ",
    block_name_en: "AFZALPUR",
    block_code: "1515001",
    panchayat_name_kn: "ಭೈರಾಮಡಗಿ",
    panchayat_name_en: "BHAIRAMADAGI",
    panchayat_code: "1515001008"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಫ್ಜಲ್‌ಪುರ",
    block_name_en: "AFZALPUR",
    block_code: "1515001",
    panchayat_name_kn: "ಬಿದನೂರ",
    panchayat_name_en: "BIDNOOR",
    panchayat_code: "1515001013"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಫ್ಜಲ್‌ಪುರ",
    block_name_en: "AFZALPUR",
    block_code: "1515001",
    panchayat_name_kn: "ಚೌಡಾಪುರ",
    panchayat_name_en: "CHOUDAPUR",
    panchayat_code: "1515001011"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಫ್ಜಲ್‌ಪುರ",
    block_name_en: "AFZALPUR",
    block_code: "1515001",
    panchayat_name_kn: "ದೇವಲ ಗಾಣಗಾಪೂರ",
    panchayat_name_en: "DEVAL GHANAGAPUR",
    panchayat_code: "1515001012"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಫ್ಜಲ್‌ಪುರ",
    block_name_en: "AFZALPUR",
    block_code: "1515001",
    panchayat_name_kn: "GHATTARGA",
    panchayat_name_en: "GHATTARGA",
    panchayat_code: "1515001025"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಫ್ಜಲ್‌ಪುರ",
    block_name_en: "AFZALPUR",
    block_code: "1515001",
    panchayat_name_kn: "ಗೋಬ್ಬುರ (ಬಿ)",
    panchayat_name_en: "GOBBUR (B)",
    panchayat_code: "1515001010"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಫ್ಜಲ್‌ಪುರ",
    block_name_en: "AFZALPUR",
    block_code: "1515001",
    panchayat_name_kn: "ಗೌರ (ಬಿ)",
    panchayat_name_en: "GOUR (B)",
    panchayat_code: "1515001009"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಫ್ಜಲ್‌ಪುರ",
    block_name_en: "AFZALPUR",
    block_code: "1515001",
    panchayat_name_kn: "ಗುಡೂರ",
    panchayat_name_en: "GUDUR",
    panchayat_code: "1515001007"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಫ್ಜಲ್‌ಪುರ",
    block_name_en: "AFZALPUR",
    block_code: "1515001",
    panchayat_name_kn: "ಹಸರಗುಂಡಗಿ",
    panchayat_name_en: "",
    panchayat_code: "1515001001"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಫ್ಜಲ್‌ಪುರ",
    block_name_en: "AFZALPUR",
    block_code: "1515001",
    panchayat_name_kn: "ಕಲ್ಲೂರ",
    panchayat_name_en: "KALLUR",
    panchayat_code: "1515001017"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಫ್ಜಲ್‌ಪುರ",
    block_name_en: "AFZALPUR",
    block_code: "1515001",
    panchayat_name_kn: "ಕರಜಗಿ",
    panchayat_name_en: "KARJAGI",
    panchayat_code: "1515001018"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಫ್ಜಲ್‌ಪುರ",
    block_name_en: "AFZALPUR",
    block_code: "1515001",
    panchayat_name_kn: "ಕೋಗನೂರ",
    panchayat_name_en: "KUGNUR",
    panchayat_code: "1515001002"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಫ್ಜಲ್‌ಪುರ",
    block_name_en: "AFZALPUR",
    block_code: "1515001",
    panchayat_name_kn: "MADARA (B)",
    panchayat_name_en: "MADARA (B)",
    panchayat_code: "1515001026"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಫ್ಜಲ್‌ಪುರ",
    block_name_en: "AFZALPUR",
    block_code: "1515001",
    panchayat_name_kn: "ಮಲ್ಲಾಬಾದ",
    panchayat_name_en: "MALLABAD",
    panchayat_code: "1515001006"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಫ್ಜಲ್‌ಪುರ",
    block_name_en: "AFZALPUR",
    block_code: "1515001",
    panchayat_name_kn: "ಮಣೂರ",
    panchayat_name_en: "MANNUR",
    panchayat_code: "1515001016"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಫ್ಜಲ್‌ಪುರ",
    block_name_en: "AFZALPUR",
    block_code: "1515001",
    panchayat_name_kn: "ಮಾಶಾಳ",
    panchayat_name_en: "MASHAL",
    panchayat_code: "1515001015"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಫ್ಜಲ್‌ಪುರ",
    block_name_en: "AFZALPUR",
    block_code: "1515001",
    panchayat_name_kn: "NANDARGA",
    panchayat_name_en: "NANDARGA",
    panchayat_code: "1515001027"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಫ್ಜಲ್‌ಪುರ",
    block_name_en: "AFZALPUR",
    block_code: "1515001",
    panchayat_name_kn: "RAMNAGAR",
    panchayat_name_en: "RAMNAGAR",
    panchayat_code: "1515001023"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಫ್ಜಲ್‌ಪುರ",
    block_name_en: "AFZALPUR",
    block_code: "1515001",
    panchayat_name_kn: "ರೇವೂರ (ಬಿ )",
    panchayat_name_en: "REVOOR (B)",
    panchayat_code: "1515001019"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಫ್ಜಲ್‌ಪುರ",
    block_name_en: "AFZALPUR",
    block_code: "1515001",
    panchayat_name_kn: "TELLUR",
    panchayat_name_en: "TELLUR",
    panchayat_code: "1515001020"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಫ್ಜಲ್‌ಪುರ",
    block_name_en: "AFZALPUR",
    block_code: "1515001",
    panchayat_name_kn: "ಉಡಚ್ಯಾಣ",
    panchayat_name_en: "UDACHAN",
    panchayat_code: "1515001005"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಳಂದ",
    block_name_en: "ALAND",
    block_code: "1515002",
    panchayat_name_kn: "ಅಳಂಗಾ",
    panchayat_name_en: "ALANGA",
    panchayat_code: "1515002013"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಳಂದ",
    block_name_en: "ALAND",
    block_code: "1515002",
    panchayat_name_kn: "ಬೆಳಮಂಗಿ",
    panchayat_name_en: "BELAMAGI",
    panchayat_code: "1515002030"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಳಂದ",
    block_name_en: "ALAND",
    block_code: "1515002",
    panchayat_name_kn: "ಭೋಧನ",
    panchayat_name_en: "BHODHAN",
    panchayat_code: "1515002039"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಳಂದ",
    block_name_en: "ALAND",
    block_code: "1515002",
    panchayat_name_kn: "ಭೂಸನೂರ",
    panchayat_name_en: "BHUSNUR",
    panchayat_code: "1515002022"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಳಂದ",
    block_name_en: "ALAND",
    block_code: "1515002",
    panchayat_name_kn: "ಚಿಂಚನಸೂರ",
    panchayat_name_en: "CHINCHANSOOR",
    panchayat_code: "1515002024"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಳಂದ",
    block_name_en: "ALAND",
    block_code: "1515002",
    panchayat_name_kn: "ದರ್ಗಾಶಿರೂರ",
    panchayat_name_en: "DARGASHIRUR",
    panchayat_code: "1515002018"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಳಂದ",
    block_name_en: "ALAND",
    block_code: "1515002",
    panchayat_name_kn: "ಧಂಗಾಪೂರ",
    panchayat_name_en: "DHANGAPUR",
    panchayat_code: "1515002004"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಳಂದ",
    block_name_en: "ALAND",
    block_code: "1515002",
    panchayat_name_kn: "DHANNUR",
    panchayat_name_en: "DHANNUR",
    panchayat_code: "1515002041"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಳಂದ",
    block_name_en: "ALAND",
    block_code: "1515002",
    panchayat_name_kn: "ದುತ್ತರಗಾಂವ",
    panchayat_name_en: "DUTTARGAON",
    panchayat_code: "1515002034"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಳಂದ",
    block_name_en: "ALAND",
    block_code: "1515002",
    panchayat_name_kn: "ಗೋಳಾ(ಬಿ)",
    panchayat_name_en: "GOLA (B)",
    panchayat_code: "1515002020"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಳಂದ",
    block_name_en: "ALAND",
    block_code: "1515002",
    panchayat_name_kn: "ಹಡಲಗಿ",
    panchayat_name_en: "HADALGI",
    panchayat_code: "1515002031"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಳಂದ",
    block_name_en: "ALAND",
    block_code: "1515002",
    panchayat_name_kn: "ಹಾಳತಡಕಲ",
    panchayat_name_en: "HALLATADAKAL",
    panchayat_code: "1515002046"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಳಂದ",
    block_name_en: "ALAND",
    block_code: "1515002",
    panchayat_name_kn: "ಹಳ್ಳಿಸಲಗರ",
    panchayat_name_en: "HALLISALAGAR",
    panchayat_code: "1515002037"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಳಂದ",
    block_name_en: "ALAND",
    block_code: "1515002",
    panchayat_name_kn: "ಹೆಬಳಿ",
    panchayat_name_en: "HEBLI",
    panchayat_code: "1515002042"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಳಂದ",
    block_name_en: "ALAND",
    block_code: "1515002",
    panchayat_name_kn: "ಹಿರೋಳ್ಳಿ",
    panchayat_name_en: "HIROLLI",
    panchayat_code: "1515002001"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಳಂದ",
    block_name_en: "ALAND",
    block_code: "1515002",
    panchayat_name_kn: "HITTALSHIRUR",
    panchayat_name_en: "HITTALSHIRUR",
    panchayat_code: "1515002044"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಳಂದ",
    block_name_en: "ALAND",
    block_code: "1515002",
    panchayat_name_kn: "ಹೋದಲುರ",
    panchayat_name_en: "HODLOOR",
    panchayat_code: "1515002006"
  },

  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಳಂದ",
    block_name_en: "ALAND",
    block_code: "1515002",
    panchayat_name_kn: "ಜಿಡಗಾ",
    panchayat_name_en: "JIDAGA",
    panchayat_code: "1515002002"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಳಂದ",
    block_name_en: "ALAND",
    block_code: "1515002",
    panchayat_name_kn: "ಕಡಗಂಚಿ",
    panchayat_name_en: "KADAGANCHI",
    panchayat_code: "1515002026"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಳಂದ",
    block_name_en: "ALAND",
    block_code: "1515002",
    panchayat_name_kn: "ಕಮಲನಗರ",
    panchayat_name_en: "KAMALANAGAR",
    panchayat_code: "1515002035"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಳಂದ",
    block_name_en: "ALAND",
    block_code: "1515002",
    panchayat_name_kn: "ಕವಲಗಾ",
    panchayat_name_en: "KAVALGA",
    panchayat_code: "1515002036"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಳಂದ",
    block_name_en: "ALAND",
    block_code: "1515002",
    panchayat_name_kn: "KERI AMBALGA",
    panchayat_name_en: "KERI+AMBALGA",
    panchayat_code: "1515002047"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಳಂದ",
    block_name_en: "ALAND",
    block_code: "1515002",
    panchayat_name_kn: "ಖಜೂರಿ",
    panchayat_name_en: "KHAJURI",
    panchayat_code: "1515002011"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಳಂದ",
    block_name_en: "ALAND",
    block_code: "1515002",
    panchayat_name_kn: "ಕಿಣ್ಣಿಸುಲ್ತಾನ",
    panchayat_name_en: "KINNI SULTAN",
    panchayat_code: "1515002012"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಳಂದ",
    block_name_en: "ALAND",
    block_code: "1515002",
    panchayat_name_kn: "ಕೋಡಲಹಂಗರ್ಗಾ",
    panchayat_name_en: "KODALHANGARGA",
    panchayat_code: "1515002008"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಳಂದ",
    block_name_en: "ALAND",
    block_code: "1515002",
    panchayat_name_kn: "ಕೋರಳ್ಳಿ",
    panchayat_name_en: "KORALLI",
    panchayat_code: "1515002009"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಳಂದ",
    block_name_en: "ALAND",
    block_code: "1515002",
    panchayat_name_kn: "ಮಾದನ ಹಿಪ್ಪರರ್ಗಾ",
    panchayat_name_en: "MADAN HIPPARGA",
    panchayat_code: "1515002029"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಳಂದ",
    block_name_en: "ALAND",
    block_code: "1515002",
    panchayat_name_kn: "ಮಡಿಯಾಳ",
    panchayat_name_en: "MADIYAL",
    panchayat_code: "1515002028"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಳಂದ",
    block_name_en: "ALAND",
    block_code: "1515002",
    panchayat_name_kn: "MATAKI",
    panchayat_name_en: "MATAKI",
    panchayat_code: "1515002038"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಳಂದ",
    block_name_en: "ALAND",
    block_code: "1515002",
    panchayat_name_kn: "ಮೋಘಾ (ಕೆ)",
    panchayat_name_en: "MOGHA+(K)",
    panchayat_code: "1515002043"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಳಂದ",
    block_name_en: "ALAND",
    block_code: "1515002",
    panchayat_name_kn: "ಮುನ್ನಳ್ಳಿ",
    panchayat_name_en: "MUNNALLI",
    panchayat_code: "1515002015"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಳಂದ",
    block_name_en: "ALAND",
    block_code: "1515002",
    panchayat_name_kn: "ನರೋಣಾ",
    panchayat_name_en: "NARONA",
    panchayat_code: "1515002032"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಳಂದ",
    block_name_en: "ALAND",
    block_code: "1515002",
    panchayat_name_kn: "ನಿಂಬಾಳ",
    panchayat_name_en: "NIMBAL",
    panchayat_code: "1515002033"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಳಂದ",
    block_name_en: "ALAND",
    block_code: "1515002",
    panchayat_name_kn: "ನಿಂಬರ್ಗಾ",
    panchayat_name_en: "NIMBARGA",
    panchayat_code: "1515002021"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಳಂದ",
    block_name_en: "ALAND",
    block_code: "1515002",
    panchayat_name_kn: "ಪಡಸಾವಣಿ",
    panchayat_name_en: "PADSAVANI",
    panchayat_code: "1515002007"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಳಂದ",
    block_name_en: "ALAND",
    block_code: "1515002",
    panchayat_name_kn: "ರುದ್ರವಾಡಿ",
    panchayat_name_en: "RUDRAWADI",
    panchayat_code: "1515002010"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಳಂದ",
    block_name_en: "ALAND",
    block_code: "1515002",
    panchayat_name_kn: "ಸರಸಂಬಾ",
    panchayat_name_en: "SARASAMBA",
    panchayat_code: "1515002017"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಳಂದ",
    block_name_en: "ALAND",
    block_code: "1515002",
    panchayat_name_kn: "ಸಾವಳೆಶ್ವರ",
    panchayat_name_en: "SAVALESHWAR",
    panchayat_code: "1515002025"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಳಂದ",
    block_name_en: "ALAND",
    block_code: "1515002",
    panchayat_name_kn: "ಸುಂಟನೂರ",
    panchayat_name_en: "SUNTNOOR",
    panchayat_code: "1515002019"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಳಂದ",
    block_name_en: "ALAND",
    block_code: "1515002",
    panchayat_name_kn: "ತಡಕಲ್‌",
    panchayat_name_en: "TADAKAL",
    panchayat_code: "1515002016"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಳಂದ",
    block_name_en: "ALAND",
    block_code: "1515002",
    panchayat_name_kn: "ತಡೋಳಾ",
    panchayat_name_en: "TADOL",
    panchayat_code: "1515002040"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಅಳಂದ",
    block_name_en: "ALAND",
    block_code: "1515002",
    panchayat_name_kn: "ಯಳಸಂಗಿ",
    panchayat_name_en: "YALSANGI",
    panchayat_code: "1515002023"
  },

  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿಂಚೋಳಿ",
    block_name_en: "CHINCHOLI",
    block_code: "1515003",
    panchayat_name_kn: "ಐನಾಪೂರ",
    panchayat_name_en: "AINAPUR",
    panchayat_code: "1515003027"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿಂಚೋಳಿ",
    block_name_en: "CHINCHOLI",
    block_code: "1515003",
    panchayat_name_kn: "ಐನೋಳ್ಳಿ",
    panchayat_name_en: "AINOLLI",
    panchayat_code: "1515003015"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿಂಚೋಳಿ",
    block_name_en: "CHINCHOLI",
    block_code: "1515003",
    panchayat_name_kn: "ಅಣವಾರ",
    panchayat_name_en: "ANWAR",
    panchayat_code: "1515003011"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿಂಚೋಳಿ",
    block_name_en: "CHINCHOLI",
    block_code: "1515003",
    panchayat_name_kn: "ಚಂದನಕೇರಾ",
    panchayat_name_en: "CHANDANKERA",
    panchayat_code: "1515003014"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿಂಚೋಳಿ",
    block_name_en: "CHINCHOLI",
    block_code: "1515003",
    panchayat_name_kn: "ಚಿಮ್ಮಾಇದ್ಲಾಯಿ",
    panchayat_name_en: "CHIMMAIDLAI",
    panchayat_code: "1515003016"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿಂಚೋಳಿ",
    block_name_en: "CHINCHOLI",
    block_code: "1515003",
    panchayat_name_kn: "ಚಿಮ್ಮನಚೋಡ",
    panchayat_name_en: "CHIMMANCHOD",
    panchayat_code: "1515003032"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿಂಚೋಳಿ",
    block_name_en: "CHINCHOLI",
    block_code: "1515003",
    panchayat_name_kn: "ದೇಗಲ್ಮಡಿ",
    panchayat_name_en: "DEGALMADI",
    panchayat_code: "1515003003"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿಂಚೋಳಿ",
    block_name_en: "CHINCHOLI",
    block_code: "1515003",
    panchayat_name_kn: "ಗಡಿಲಿಂಗದಳ್ಳಿ",
    panchayat_name_en: "GADILINGADALLI",
    panchayat_code: "1515003017"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿಂಚೋಳಿ",
    block_name_en: "CHINCHOLI",
    block_code: "1515003",
    panchayat_name_kn: "ಗರಗಪಳ್ಳಿ",
    panchayat_name_en: "GARAGAPPANA",
    panchayat_code: "1515003033"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿಂಚೋಳಿ",
    block_name_en: "CHINCHOLI",
    block_code: "1515003",
    panchayat_name_kn: "GARAMPALLI",
    panchayat_name_en: "GARAMPALLI",
    panchayat_code: "1515003036"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿಂಚೋಳಿ",
    block_name_en: "CHINCHOLI",
    block_code: "1515003",
    panchayat_name_kn: "ಹಸರಗುಂಡಗಿ",
    panchayat_name_en: "HASARGUNDAGI",
    panchayat_code: "1515003026"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿಂಚೋಳಿ",
    block_name_en: "CHINCHOLI",
    block_code: "1515003",
    panchayat_name_kn: "JATTUR",
    panchayat_name_en: "JATTUR",
    panchayat_code: "1515003034"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿಂಚೋಳಿ",
    block_name_en: "CHINCHOLI",
    block_code: "1515003",
    panchayat_name_kn: "ಕನಕಪೂರ",
    panchayat_name_en: "KANAKPUR (KARAKMUKLI)",
    panchayat_code: "1515003028"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿಂಚೋಳಿ",
    block_name_en: "CHINCHOLI",
    block_code: "1515003",
    panchayat_name_kn: "ಕರ್ಚಖೇಡ",
    panchayat_name_en: "KARCHKHED",
    panchayat_code: "1515003029"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿಂಚೋಳಿ",
    block_name_en: "CHINCHOLI",
    block_code: "1515003",
    panchayat_name_kn: "ಕೆರೋಳ್ಳಿ",
    panchayat_name_en: "KEROLLI",
    panchayat_code: "1515003019"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿಂಚೋಳಿ",
    block_name_en: "CHINCHOLI",
    block_code: "1515003",
    panchayat_name_kn: "ಕೊಂಚಾವರಂ",
    panchayat_name_en: "KUNCHAVARAM",
    panchayat_code: "1515003020"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿಂಚೋಳಿ",
    block_name_en: "CHINCHOLI",
    block_code: "1515003",
    panchayat_name_kn: "ಕುಪನೂರ",
    panchayat_name_en: "KUPANOOR",
    panchayat_code: "1515003035"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿಂಚೋಳಿ",
    block_name_en: "CHINCHOLI",
    block_code: "1515003",
    panchayat_name_kn: "ಮಿರಿಯಾಣ",
    panchayat_name_en: "MIRIYAN",
    panchayat_code: "1515003007"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿಂಚೋಳಿ",
    block_name_en: "CHINCHOLI",
    block_code: "1515003",
    panchayat_name_kn: "ನಾಗಾಇದ್ಲಾಯಿ",
    panchayat_name_en: "NAGAIDLAI",
    panchayat_code: "1515003009"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿಂಚೋಳಿ",
    block_name_en: "CHINCHOLI",
    block_code: "1515003",
    panchayat_name_kn: "ನಿಡಗುಂದಾ",
    panchayat_name_en: "NIDAGUNDA",
    panchayat_code: "1515003030"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿಂಚೋಳಿ",
    block_name_en: "CHINCHOLI",
    block_code: "1515003",
    panchayat_name_kn: "ಪೋಲಕಪಳ್ಲಿ",
    panchayat_name_en: "POLAKPALLI",
    panchayat_code: "1515003004"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿಂಚೋಳಿ",
    block_name_en: "CHINCHOLI",
    block_code: "1515003",
    panchayat_name_kn: "ಸಾಲೆಬೀರನಳ್ಳಿ",
    panchayat_name_en: "SALEBEERNALLI",
    panchayat_code: "1515003012"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿಂಚೋಳಿ",
    block_name_en: "CHINCHOLI",
    block_code: "1515003",
    panchayat_name_kn: "ಸಲಗರ ಬಸಂತಪೂರ",
    panchayat_name_en: "SALGAR BASANTPUR",
    panchayat_code: "1515003005"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿಂಚೋಳಿ",
    block_name_en: "CHINCHOLI",
    block_code: "1515003",
    panchayat_name_kn: "ಶಾದಿಪೂರ",
    panchayat_name_en: "SHADIPUR",
    panchayat_code: "1515003022"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿಂಚೋಳಿ",
    block_name_en: "CHINCHOLI",
    block_code: "1515003",
    panchayat_name_kn: "ಶಿರೋಳ್ಳಿ",
    panchayat_name_en: "SHIROLLI",
    panchayat_code: "1515003023"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿಂಚೋಳಿ",
    block_name_en: "CHINCHOLI",
    block_code: "1515003",
    panchayat_name_kn: "ಸುಲೇಪೇಟ",
    panchayat_name_en: "SULEPETH",
    panchayat_code: "1515003024"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿಂಚೋಳಿ",
    block_name_en: "CHINCHOLI",
    block_code: "1515003",
    panchayat_name_kn: "ವೆಂಕಟಾಪೂರ",
    panchayat_name_en: "VENKATAPUR",
    panchayat_code: "1515003002"
  },

  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿತಾಪುರ",
    block_name_en: "CHITAPUR",
    block_code: "1515004",
    panchayat_name_kn: "ಅಳ್ಳೊಳ್ಳಿ",
    panchayat_name_en: "ALLOLI",
    panchayat_code: "1515004001"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿತಾಪುರ",
    block_name_en: "CHITAPUR",
    block_code: "1515004",
    panchayat_name_kn: "ಅಲ್ಲೂರ(ಬಿ)",
    panchayat_name_en: "ALLUR (B)",
    panchayat_code: "1515004002"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿತಾಪುರ",
    block_name_en: "CHITAPUR",
    block_code: "1515004",
    panchayat_name_kn: "ಭಾಗೋಡಿ",
    panchayat_name_en: "BHAGODI",
    panchayat_code: "1515004004"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿತಾಪುರ",
    block_name_en: "CHITAPUR",
    block_code: "1515004",
    panchayat_name_kn: "ಭೀಮನಳ್ಳಿ",
    panchayat_name_en: "BHIMANALLI",
    panchayat_code: "1515004006"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿತಾಪುರ",
    block_name_en: "CHITAPUR",
    block_code: "1515004",
    panchayat_name_kn: "ದಂಡೋತಿ",
    panchayat_name_en: "DANDOTHI",
    panchayat_code: "1515004008"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿತಾಪುರ",
    block_name_en: "CHITAPUR",
    block_code: "1515004",
    panchayat_name_kn: "ಡೋಣಗಾಂವ",
    panchayat_name_en: "DHONGAON",
    panchayat_code: "1515004041"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿತಾಪುರ",
    block_name_en: "CHITAPUR",
    block_code: "1515004",
    panchayat_name_kn: "ದಿಗ್ಗಾಂವ",
    panchayat_name_en: "DIGGAON",
    panchayat_code: "1515004009"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿತಾಪುರ",
    block_name_en: "CHITAPUR",
    block_code: "1515004",
    panchayat_name_kn: "ಗುಂಡಗುರ್ತಿ",
    panchayat_name_en: "GUNDAGURTHI",
    panchayat_code: "1515004010"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿತಾಪುರ",
    block_name_en: "CHITAPUR",
    block_code: "1515004",
    panchayat_name_kn: "ಹಲಕಟ್ಟಾ",
    panchayat_name_en: "HALKATTA",
    panchayat_code: "1515004012"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿತಾಪುರ",
    block_name_en: "CHITAPUR",
    block_code: "1515004",
    panchayat_name_kn: "ಇಂಗಳಗಿ",
    panchayat_name_en: "INGALAGI",
    panchayat_code: "1515004015"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿತಾಪುರ",
    block_name_en: "CHITAPUR",
    block_code: "1515004",
    panchayat_name_kn: "IVANI",
    panchayat_name_en: "IVANI",
    panchayat_code: "1515004037"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿತಾಪುರ",
    block_name_en: "CHITAPUR",
    block_code: "1515004",
    panchayat_name_kn: "ಕಡಬೂರ",
    panchayat_name_en: "KADBUR",
    panchayat_code: "1515004016"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿತಾಪುರ",
    block_name_en: "CHITAPUR",
    block_code: "1515004",
    panchayat_name_kn: "ಕಮರವಾಡಿ",
    panchayat_name_en: "KAMARWADI",
    panchayat_code: "1515004003"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿತಾಪುರ",
    block_name_en: "CHITAPUR",
    block_code: "1515004",
    panchayat_name_kn: "KARDAL",
    panchayat_name_en: "KARDAL",
    panchayat_code: "1515004040"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿತಾಪುರ",
    block_name_en: "CHITAPUR",
    block_code: "1515004",
    panchayat_name_kn: "ಕೊಲ್ಲೂರ",
    panchayat_name_en: "KOLLUR",
    panchayat_code: "1515004021"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿತಾಪುರ",
    block_name_en: "CHITAPUR",
    block_code: "1515004",
    panchayat_name_kn: "ಲಾಡ್ಲಾಪೂರ",
    panchayat_name_en: "LADLAPUR",
    panchayat_code: "1515004023"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿತಾಪುರ",
    block_name_en: "CHITAPUR",
    block_code: "1515004",
    panchayat_name_kn: "MOGALA",
    panchayat_name_en: "MOGALA",
    panchayat_code: "1515004038"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿತಾಪುರ",
    block_name_en: "CHITAPUR",
    block_code: "1515004",
    panchayat_name_kn: "ನಾಲವಾರ",
    panchayat_name_en: "NALWAR",
    panchayat_code: "1515004027"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿತಾಪುರ",
    block_name_en: "CHITAPUR",
    block_code: "1515004",
    panchayat_name_kn: "RAMPURHALLI",
    panchayat_name_en: "RAMPURHALLI",
    panchayat_code: "1515004043"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿತಾಪುರ",
    block_name_en: "CHITAPUR",
    block_code: "1515004",
    panchayat_name_kn: "ಸನ್ನತಿ",
    panchayat_name_en: "SANNATI",
    panchayat_code: "1515004031"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿತಾಪುರ",
    block_name_en: "CHITAPUR",
    block_code: "1515004",
    panchayat_name_kn: "ಸಾತನೂರ",
    panchayat_name_en: "SATNOOR",
    panchayat_code: "1515004032"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಚಿತಾಪುರ",
    block_name_en: "CHITAPUR",
    block_code: "1515004",
    panchayat_name_kn: "ಯಾಗಾಪೂರ",
    panchayat_name_en: "YAGAPUR",
    panchayat_code: "1515004035"
  },

  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಜೇವರ್ಗಿ",
    block_name_en: "JEVARGI",
    block_code: "1515006",
    panchayat_name_kn: "ಅಂದೋಲಾ",
    panchayat_name_en: "ANDHOLA",
    panchayat_code: "1515006008"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಜೇವರ್ಗಿ",
    block_name_en: "JEVARGI",
    block_code: "1515006",
    panchayat_name_kn: "ಅಂಕಲಗಾ",
    panchayat_name_en: "ANKALGA",
    panchayat_code: "1515006032"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಜೇವರ್ಗಿ",
    block_name_en: "JEVARGI",
    block_code: "1515006",
    panchayat_name_kn: "ಬಳುಂಡಗಿ",
    panchayat_name_en: "BALUNDAGI",
    panchayat_code: "1515006031"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಜೇವರ್ಗಿ",
    block_name_en: "JEVARGI",
    block_code: "1515006",
    panchayat_name_kn: "ಬಿರಾಳ.ಬಿ",
    panchayat_name_en: "BIRAL (B)",
    panchayat_code: "1515006009"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಜೇವರ್ಗಿ",
    block_name_en: "JEVARGI",
    block_code: "1515006",
    panchayat_name_kn: "ಗಂವಾರ",
    panchayat_name_en: "GAONVAR",
    panchayat_code: "1515006012"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಜೇವರ್ಗಿ",
    block_name_en: "JEVARGI",
    block_code: "1515006",
    panchayat_name_kn: "ಗೂಡೂರ.ಎಸ್‌.ಎ",
    panchayat_name_en: "GUDUR-S-A",
    panchayat_code: "1515006007"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಜೇವರ್ಗಿ",
    block_name_en: "JEVARGI",
    block_code: "1515006",
    panchayat_name_kn: "ಹರಸೂರ",
    panchayat_name_en: "HARANOOR",
    panchayat_code: "1515006011"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಜೇವರ್ಗಿ",
    block_name_en: "JEVARGI",
    block_code: "1515006",
    panchayat_name_kn: "ಹರವಾಳ",
    panchayat_name_en: "HARWAL",
    panchayat_code: "1515006003"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಜೇವರ್ಗಿ",
    block_name_en: "JEVARGI",
    block_code: "1515006",
    panchayat_name_kn: "ಹಿಪ್ಪರಗಾ.ಎಸ್‌.ಎನ್‌",
    panchayat_name_en: "HIPPARGA -S-N",
    panchayat_code: "1515006020"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಜೇವರ್ಗಿ",
    block_name_en: "JEVARGI",
    block_code: "1515006",
    panchayat_name_kn: "HULLUR",
    panchayat_name_en: "HULLUR",
    panchayat_code: "1515006042"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಜೇವರ್ಗಿ",
    block_name_en: "JEVARGI",
    block_code: "1515006",
    panchayat_name_kn: "ಇಟಗಾ",
    panchayat_name_en: "ITGA",
    panchayat_code: "1515006033"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಜೇವರ್ಗಿ",
    block_name_en: "JEVARGI",
    block_code: "1515006",
    panchayat_name_kn: "ಜೇರಟಗಿ",
    panchayat_name_en: "JERATAGI",
    panchayat_code: "1515006030"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಜೇವರ್ಗಿ",
    block_name_en: "JEVARGI",
    block_code: "1515006",
    panchayat_name_kn: "KALHANGARGA",
    panchayat_name_en: "KALHANGARGA",
    panchayat_code: "1515006034"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಜೇವರ್ಗಿ",
    block_name_en: "JEVARGI",
    block_code: "1515006",
    panchayat_name_kn: "ಕಲ್ಲೂರ.ಕೆ",
    panchayat_name_en: "KALLUR (K)",
    panchayat_code: "1515006002"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಜೇವರ್ಗಿ",
    block_name_en: "JEVARGI",
    block_code: "1515006",
    panchayat_name_kn: "ಕೆಲ್ಲೂರ",
    panchayat_name_en: "KELLUR",
    panchayat_code: "1515006010"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಜೇವರ್ಗಿ",
    block_name_en: "JEVARGI",
    block_code: "1515006",
    panchayat_name_kn: "ಕೊಳಕೂರ",
    panchayat_name_en: "KOLKUR",
    panchayat_code: "1515006004"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಜೇವರ್ಗಿ",
    block_name_en: "JEVARGI",
    block_code: "1515006",
    panchayat_name_kn: "ಕೂಡಿ",
    panchayat_name_en: "KOODI",
    panchayat_code: "1515006005"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಜೇವರ್ಗಿ",
    block_name_en: "JEVARGI",
    block_code: "1515006",
    panchayat_name_kn: "MADARI",
    panchayat_name_en: "MADARI",
    panchayat_code: "1515006037"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಜೇವರ್ಗಿ",
    block_name_en: "JEVARGI",
    block_code: "1515006",
    panchayat_name_kn: "ಮಂದೇವಾಲ",
    panchayat_name_en: "MANDEWAL",
    panchayat_code: "1515006029"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಜೇವರ್ಗಿ",
    block_name_en: "JEVARGI",
    block_code: "1515006",
    panchayat_name_kn: "ನರಿಬೋಳ",
    panchayat_name_en: "NARIBOL",
    panchayat_code: "1515006006"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಜೇವರ್ಗಿ",
    block_name_en: "JEVARGI",
    block_code: "1515006",
    panchayat_name_kn: "ನೇದಲಗಿ",
    panchayat_name_en: "NEDALGI",
    panchayat_code: "1515006041"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಜೇವರ್ಗಿ",
    block_name_en: "JEVARGI",
    block_code: "1515006",
    panchayat_name_kn: "ನೆಲೋಗಿ",
    panchayat_name_en: "NELOGI",
    panchayat_code: "1515006001"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಜೇವರ್ಗಿ",
    block_name_en: "JEVARGI",
    block_code: "1515006",
    panchayat_name_kn: "ರಂಜಣಗಿ",
    panchayat_name_en: "RANJANGI",
    panchayat_code: "1515006040"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಜೇವರ್ಗಿ",
    block_name_en: "JEVARGI",
    block_code: "1515006",
    panchayat_name_kn: "ಸೊನ್ನ",
    panchayat_name_en: "SONNA",
    panchayat_code: "1515006015"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಜೇವರ್ಗಿ",
    block_name_en: "JEVARGI",
    block_code: "1515006",
    panchayat_name_kn: "ಯಾಳವಾರ",
    panchayat_name_en: "YALWAR",
    panchayat_code: "1515006013"
  },

  //________________________

  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಗುಲ್ಬರ್ಗಾ",
    block_name_en: "KALABURAGI",
    block_code: "1515005",
    panchayat_name_kn: "ALGOOD",
    panchayat_name_en: "ALGOOD",
    panchayat_code: "1515005037"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಗುಲ್ಬರ್ಗಾ",
    block_name_en: "KALABURAGI",
    block_code: "1515005",
    panchayat_name_kn: "ಅವರಾದ (ಬಿ)",
    panchayat_name_en: "AURAD (B)",
    panchayat_code: "1515005007"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಗುಲ್ಬರ್ಗಾ",
    block_name_en: "KALABURAGI",
    block_code: "1515005",
    panchayat_name_kn: "BASAVAPATTAN",
    panchayat_name_en: "BASAVAPATTAN",
    panchayat_code: "1515005040"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಗುಲ್ಬರ್ಗಾ",
    block_name_en: "KALABURAGI",
    block_code: "1515005",
    panchayat_name_kn: "ಭೀಮಳ್ಳಿ",
    panchayat_name_en: "BHIMALLI",
    panchayat_code: "1515005035"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಗುಲ್ಬರ್ಗಾ",
    block_name_en: "KALABURAGI",
    block_code: "1515005",
    panchayat_name_kn: "ಭೂಪಾಲತೆಗನೂರ",
    panchayat_name_en: "BHUPALTEGANOOR",
    panchayat_code: "1515005019"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಗುಲ್ಬರ್ಗಾ",
    block_name_en: "KALABURAGI",
    block_code: "1515005",
    panchayat_name_kn: "ಫರಹತಾಬಾದ",
    panchayat_name_en: "FARAHATABAD",
    panchayat_code: "1515005030"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಗುಲ್ಬರ್ಗಾ",
    block_name_en: "KALABURAGI",
    block_code: "1515005",
    panchayat_name_kn: "ಫೀರೋಜಾಬಾದ",
    panchayat_name_en: "FHIROZABAD",
    panchayat_code: "1515005010"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಗುಲ್ಬರ್ಗಾ",
    block_name_en: "KALABURAGI",
    block_code: "1515005",
    panchayat_name_kn: "HAGARGA",
    panchayat_name_en: "HAGARGA",
    panchayat_code: "1515005038"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಗುಲ್ಬರ್ಗಾ",
    block_name_en: "KALABURAGI",
    block_code: "1515005",
    panchayat_name_kn: "ಹರಸೂರ",
    panchayat_name_en: "HARSOOR",
    panchayat_code: "1515005015"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಗುಲ್ಬರ್ಗಾ",
    block_name_en: "KALABURAGI",
    block_code: "1515005",
    panchayat_name_kn: "ಹೇರೂರ(ಬಿ)",
    panchayat_name_en: "HEROOR (B)",
    panchayat_code: "1515005020"
  },
  {
    district_name_kn: "ಕಲಬುरಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಗುಲ್ಬರ್ಗಾ",
    block_name_en: "KALABURAGI",
    block_code: "1515005",
    panchayat_name_kn: "ಹೊನ್ನ ಕಿರಣಗಿ",
    panchayat_name_en: "HONNA KIRANAGI",
    panchayat_code: "1515005029"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಗುಲ್ಬರ್ಗಾ",
    block_name_en: "KALABURAGI",
    block_code: "1515005",
    panchayat_name_kn: "ಕಡಣಿ",
    panchayat_name_en: "KADANI",
    panchayat_code: "1515005018"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಗುಲ್ಬರ್ಗಾ",
    block_name_en: "KALABURAGI",
    block_code: "1515005",
    panchayat_name_kn: "ಕಲ್ಲೂರ",
    panchayat_name_en: "KALLAHANGARGA",
    panchayat_code: "1515005034"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಗುಲ್ಬರ್ಗಾ",
    block_name_en: "KALABURAGI",
    block_code: "1515005",
    panchayat_name_kn: "ಕವಲಗಾ (ಬಿ)",
    panchayat_name_en: "KAVALGA (B)",
    panchayat_code: "1515005003"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಗುಲ್ಬರ್ಗಾ",
    block_name_en: "KALABURAGI",
    block_code: "1515005",
    panchayat_name_kn: "ಖಣದಾಳ",
    panchayat_name_en: "KHANADAL",
    panchayat_code: "1515005026"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಗುಲ್ಬರ್ಗಾ",
    block_name_en: "KALABURAGI",
    block_code: "1515005",
    panchayat_name_kn: "ಕುಮಸಿ",
    panchayat_name_en: "KUMASI",
    panchayat_code: "1515005011"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಗುಲ್ಬರ್ಗಾ",
    block_name_en: "KALABURAGI",
    block_code: "1515005",
    panchayat_name_kn: "ಕುಸನೂರ",
    panchayat_name_en: "KUSANOOR",
    panchayat_code: "1515005032"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಗುಲ್ಬರ್ಗಾ",
    block_name_en: "KALABURAGI",
    block_code: "1515005",
    panchayat_name_kn: "ಮೇಳಕುಂದಾ (ಬಿ)",
    panchayat_name_en: "MELAKUNDA (B)",
    panchayat_code: "1515005006"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಗುಲ್ಬರ್ಗಾ",
    block_name_en: "KALABURAGI",
    block_code: "1515005",
    panchayat_name_kn: "MINIJAGI",
    panchayat_name_en: "MINIJAGI",
    panchayat_code: "1515005041"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಗುಲ್ಬರ್ಗಾ",
    block_name_en: "KALABURAGI",
    block_code: "1515005",
    panchayat_name_kn: "ನಂದಿಕೂರ",
    panchayat_name_en: "NANDIKUR",
    panchayat_code: "1515005009"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಗುಲ್ಬರ್ಗಾ",
    block_name_en: "KALABURAGI",
    block_code: "1515005",
    panchayat_name_kn: "ನಂದೂರ (ಕೆ)",
    panchayat_name_en: "NANDUR (K)",
    panchayat_code: "1515005031"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಗುಲ್ಬರ್ಗಾ",
    block_name_en: "KALABURAGI",
    block_code: "1515005",
    panchayat_name_kn: "ಪಟ್ಟಣ",
    panchayat_name_en: "PATTAN",
    panchayat_code: "1515005025"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಗುಲ್ಬರ್ಗಾ",
    block_name_en: "KALABURAGI",
    block_code: "1515005",
    panchayat_name_kn: "ಸಣ್ಣೂರ",
    panchayat_name_en: "SANNUR",
    panchayat_code: "1515005008"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಗುಲ್ಬರ್ಗಾ",
    block_name_en: "KALABURAGI",
    block_code: "1515005",
    panchayat_name_kn: "SARADAGI (B)",
    panchayat_name_en: "SARADAGI (B)",
    panchayat_code: "1515005004"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಗುಲ್ಬರ್ಗಾ",
    block_name_en: "KALABURAGI",
    block_code: "1515005",
    panchayat_name_kn: "ಸಾವಳಗಿ (ಬಿ)",
    panchayat_name_en: "SAVALGI (B)",
    panchayat_code: "1515005004"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಗುಲ್ಬರ್ಗಾ",
    block_name_en: "KALABURAGI",
    block_code: "1515005",
    panchayat_name_kn: "ಶರಣ ಸಿರಸಗಿ",
    panchayat_name_en: "SHARAN SIRASAGI",
    panchayat_code: "1515005016"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಗುಲ್ಬರ್ಗಾ",
    block_name_en: "KALABURAGI",
    block_code: "1515005",
    panchayat_name_kn: "ಶ್ರೀನಿವಾಸ ಸರಡಗಿ",
    panchayat_name_en: "SRINIVAS SARADGI",
    panchayat_code: "1515005036"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಗುಲ್ಬರ್ಗಾ",
    block_name_en: "KALABURAGI",
    block_code: "1515005",
    panchayat_name_kn: "ತಾಜಸುಲ್ತಾನಪೂರ",
    panchayat_name_en: "TAJSULTANPUR",
    panchayat_code: "1515005023"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಕಾಳಗಿ",
    block_name_en: "KALAGI",
    block_code: "1515011",
    panchayat_name_kn: "ಅರಣಕಲ",
    panchayat_name_en: "ARANKAL",
    panchayat_code: "1515004018"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಕಾಳಗಿ",
    block_name_en: "KALAGI",
    block_code: "1515011",
    panchayat_name_kn: "ಬೆಡಸೂರ",
    panchayat_name_en: "BEDSUR",
    panchayat_code: "1515004036"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಕಾಳಗಿ",
    block_name_en: "KALAGI",
    block_code: "1515011",
    panchayat_name_kn: "ಚಿಂಚೊಳ್ಳಿ(ಎಚ್)",
    panchayat_name_en: "CHINCHOLLI (H)",
    panchayat_code: "1515004007"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಕಾಳಗಿ",
    block_name_en: "KALAGI",
    block_code: "1515011",
    panchayat_name_kn: "ಗಡಿಕೇಶ್ವಾರ",
    panchayat_name_en: "GADIKESHWAR",
    panchayat_code: "1515003013"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಕಾಳಗಿ",
    block_name_en: "KALAGI",
    block_code: "1515011",
    panchayat_name_kn: "ಗೋಟೂರ",
    panchayat_name_en: "GOTOOR",
    panchayat_code: "1515004011"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಕಾಳಗಿ",
    block_name_en: "KALAGI",
    block_code: "1515011",
    panchayat_name_kn: "ಹಲಚೇರಾ",
    panchayat_name_en: "HALCHERA",
    panchayat_code: "1515003018"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಕಾಳಗಿ",
    block_name_en: "KALAGI",
    block_code: "1515011",
    panchayat_name_kn: "ಹೆಬ್ಬಾಳ",
    panchayat_name_en: "HEBBAL",
    panchayat_code: "1515004013"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಕಾಳಗಿ",
    block_name_en: "KALAGI",
    block_code: "1515011",
    panchayat_name_kn: "ಹೊಡೆಬೀರನಳ್ಳಿ",
    panchayat_name_en: "HODEBEERNALLI",
    panchayat_code: "1515003001"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಕಾಳಗಿ",
    block_name_en: "KALAGI",
    block_code: "1515011",
    panchayat_name_kn: "ಕಂದಗೋಳ",
    panchayat_name_en: "KANDGOL",
    panchayat_code: "1515004019"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಕಾಳಗಿ",
    block_name_en: "KALAGI",
    block_code: "1515011",
    panchayat_name_kn: "ಕೋಡದೂರ",
    panchayat_name_en: "KODADUR",
    panchayat_code: "1515004020"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಕಾಳಗಿ",
    block_name_en: "KALAGI",
    block_code: "1515011",
    panchayat_name_kn: "ಕೋಡ್ಲಿ",
    panchayat_name_en: "KODLI",
    panchayat_code: "1515003010"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಕಾಳಗಿ",
    block_name_en: "KALAGI",
    block_code: "1515011",
    panchayat_name_kn: "ಕೋರವಾರ",
    panchayat_name_en: "KORWAR",
    panchayat_code: "1515004022"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಕಾಳಗಿ",
    block_name_en: "KALAGI",
    block_code: "1515011",
    panchayat_name_kn: "ಮಾಡಬೂಳ",
    panchayat_name_en: "MADBUL",
    panchayat_code: "1515004024"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಕಾಳಗಿ",
    block_name_en: "KALAGI",
    block_code: "1515011",
    panchayat_name_kn: "ಮೋಘಾ",
    panchayat_name_en: "MOGHA",
    panchayat_code: "1515003006"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಕಾಳಗಿ",
    block_name_en: "KALAGI",
    block_code: "1515011",
    panchayat_name_kn: "ಪಸ್ತಪೂರ",
    panchayat_name_en: "PASTAPUR",
    panchayat_code: "1515003008"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಕಾಳಗಿ",
    block_name_en: "KALAGI",
    block_code: "1515011",
    panchayat_name_kn: "ಪೇಠ ಶಿರೂರ",
    panchayat_name_en: "PETHSIROOR",
    panchayat_code: "1515004028"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಕಾಳಗಿ",
    block_name_en: "KALAGI",
    block_code: "1515011",
    panchayat_name_kn: "ರಾಜಾಪೂರ",
    panchayat_name_en: "RAJAPUR",
    panchayat_code: "1515004029"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಕಾಳಗಿ",
    block_name_en: "KALAGI",
    block_code: "1515011",
    panchayat_name_kn: "ರಟಕಲ",
    panchayat_name_en: "RATKAL",
    panchayat_code: "1515003021"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಕಾಳಗಿ",
    block_name_en: "KALAGI",
    block_code: "1515011",
    panchayat_name_kn: "ರುಮ್ಮನಗೂಡ",
    panchayat_name_en: "RUMMANGUD",
    panchayat_code: "1515003031"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಕಾಳಗಿ",
    block_name_en: "KALAGI",
    block_code: "1515011",
    panchayat_name_kn: "SHELLAGI",
    panchayat_name_en: "SHELLAGI",
    panchayat_code: "1515004042"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಕಾಳಗಿ",
    block_name_en: "KALAGI",
    block_code: "1515011",
    panchayat_name_kn: "ಟೆಂಗಳಿ",
    panchayat_name_en: "TENGALI",
    panchayat_code: "1515004033"
  },

  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಕಮಲಾಪುರ",
    block_name_en: "KAMALAPUR",
    block_code: "1515012",
    panchayat_name_kn: "ಅಂಬಲಗಾ",
    panchayat_name_en: "AMBALGA",
    panchayat_code: "1515002014"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಕಮಲಾಪುರ",
    block_name_en: "KAMALAPUR",
    block_code: "1515012",
    panchayat_name_kn: "ಬಬಲಾದ (ಐಕೆ)",
    panchayat_name_en: "BABALAD (IK)",
    panchayat_code: "1515005033"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಕಮಲಾಪುರ",
    block_name_en: "KAMALAPUR",
    block_code: "1515012",
    panchayat_name_kn: "ಚೇಂಗಟಾ",
    panchayat_name_en: "CHENGTA",
    panchayat_code: "1515003025"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಕಮಲಾಪುರ",
    block_name_en: "KAMALAPUR",
    block_code: "1515012",
    panchayat_name_kn: "ಡೊಂಗರಗಾಂವ",
    panchayat_name_en: "DONGARGOAN",
    panchayat_code: "1515005014"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಕಮಲಾಪುರ",
    block_name_en: "KAMALAPUR",
    block_code: "1515012",
    panchayat_name_kn: "ಹೋಳಕುಂದಾ",
    panchayat_name_en: "HOLAKUNDA",
    panchayat_code: "1515005001"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಕಮಲಾಪುರ",
    block_name_en: "KAMALAPUR",
    block_code: "1515012",
    panchayat_name_kn: "ಜೀವಣಗಿ",
    panchayat_name_en: "JEEVANGI",
    panchayat_code: "1515005005"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಕಮಲಾಪುರ",
    block_name_en: "KAMALAPUR",
    block_code: "1515012",
    panchayat_name_kn: "ಕಲ್ಮೂಡ",
    panchayat_name_en: "KALMOOD",
    panchayat_code: "1515005022"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಕಮಲಾಪುರ",
    block_name_en: "KAMALAPUR",
    block_code: "1515012",
    panchayat_name_kn: "ಕಿಣ್ಣಿಸಡಕ",
    panchayat_name_en: "KINNISADAK",
    panchayat_code: "1515005024"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಕಮಲಾಪುರ",
    block_name_en: "KAMALAPUR",
    block_code: "1515012",
    panchayat_name_kn: "ಕುರಿಕೋಟಾ",
    panchayat_name_en: "KURIKOTA",
    panchayat_code: "1515005012"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಕಮಲಾಪುರ",
    block_name_en: "KAMALAPUR",
    block_code: "1515012",
    panchayat_name_kn: "ಲಾಡಮುಗಳಿ",
    panchayat_name_en: "LAD MUGALI",
    panchayat_code: "1515002005"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಕಮಲಾಪುರ",
    block_name_en: "KAMALAPUR",
    block_code: "1515012",
    panchayat_name_kn: "MADAKI",
    panchayat_name_en: "MADAKI",
    panchayat_code: "1515002045"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಕಮಲಾಪುರ",
    block_name_en: "KAMALAPUR",
    block_code: "1515012",
    panchayat_name_kn: "ಮಹಾಗಾಂವ",
    panchayat_name_en: "MAHAGOAN",
    panchayat_code: "1515005027"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಕಮಲಾಪುರ",
    block_name_en: "KAMALAPUR",
    block_code: "1515012",
    panchayat_name_kn: "ಮರಗುತ್ತಿ",
    panchayat_name_en: "MARAGUTTI",
    panchayat_code: "1515005002"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಕಮಲಾಪುರ",
    block_name_en: "KAMALAPUR",
    block_code: "1515012",
    panchayat_name_kn: "ನಾಗೂರ",
    panchayat_name_en: "NAGUR",
    panchayat_code: "1515005028"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಕಮಲಾಪುರ",
    block_name_en: "KAMALAPUR",
    block_code: "1515012",
    panchayat_name_kn: "ಓಕಳಿ",
    panchayat_name_en: "OKALI",
    panchayat_code: "1515005013"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಕಮಲಾಪುರ",
    block_name_en: "KAMALAPUR",
    block_code: "1515012",
    panchayat_name_kn: "ಶ್ರಿಚಂದ",
    panchayat_name_en: "SHRICHAND",
    panchayat_code: "1515002003"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಕಮಲಾಪುರ",
    block_name_en: "KAMALAPUR",
    block_code: "1515012",
    panchayat_name_kn: "ಸೊಂತ",
    panchayat_name_en: "SONTH",
    panchayat_code: "1515005017"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಕಮಲಾಪುರ",
    block_name_en: "KAMALAPUR",
    block_code: "1515012",
    panchayat_name_kn: "ವ್ಹಿ.ಕೆ.ಸಲಗರ",
    panchayat_name_en: "V.K.SALGAR",
    panchayat_code: "1515002027"
  },

  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಸೆಡಂ",
    block_name_en: "SEDAM",
    block_code: "1515007",
    panchayat_name_kn: "ಅಡಕಿ",
    panchayat_name_en: "ADAKI",
    panchayat_code: "1515007021"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಸೆಡಂ",
    block_name_en: "SEDAM",
    block_code: "1515007",
    panchayat_name_kn: "ಬಟಗೇರಾ",
    panchayat_name_en: "BATAGERA -K",
    panchayat_code: "1515007001"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಸೆಡಂ",
    block_name_en: "SEDAM",
    block_code: "1515007",
    panchayat_name_kn: "BENAKANAHA",
    panchayat_name_en: "BENAKANAHA",
    panchayat_code: "1515007024"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಸೆಡಂ",
    block_name_en: "SEDAM",
    block_code: "1515007",
    panchayat_name_kn: "CHANDAPUR",
    panchayat_name_en: "CHANDAPUR",
    panchayat_code: "1515007025"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಸೆಡಂ",
    block_name_en: "SEDAM",
    block_code: "1515007",
    panchayat_name_kn: "ದುಗನೂರ",
    panchayat_name_en: "DUGNOOR",
    panchayat_code: "1515007009"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಸೆಡಂ",
    block_name_en: "SEDAM",
    block_code: "1515007",
    panchayat_name_kn: "ಹಂದರಕಿ",
    panchayat_name_en: "HANDARKI",
    panchayat_code: "1515007012"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಸೆಡಂ",
    block_name_en: "SEDAM",
    block_code: "1515007",
    panchayat_name_kn: "ಇಟಕಾಲ",
    panchayat_name_en: "ITKAL",
    panchayat_code: "1515007019"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಸೆಡಂ",
    block_name_en: "SEDAM",
    block_code: "1515007",
    panchayat_name_kn: "ಜಾಕನಪಲ್ಲಿ",
    panchayat_name_en: "JAKANPALLI",
    panchayat_code: "1515007022"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಸೆಡಂ",
    block_name_en: "SEDAM",
    block_code: "1515007",
    panchayat_name_kn: "ಕಾನಾಗಡ್ಡಾ",
    panchayat_name_en: "KANAGADDA",
    panchayat_code: "1515007015"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಸೆಡಂ",
    block_name_en: "SEDAM",
    block_code: "1515007",
    panchayat_name_kn: "ಕೊಲಕುಂದಾ",
    panchayat_name_en: "KOLKUNDA",
    panchayat_code: "1515007003"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಸೆಡಂ",
    block_name_en: "SEDAM",
    block_code: "1515007",
    panchayat_name_kn: "ಕೊಡ್ಲಾ",
    panchayat_name_en: "KUDLA",
    panchayat_code: "1515007008"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಸೆಡಂ",
    block_name_en: "SEDAM",
    block_code: "1515007",
    panchayat_name_kn: "ಕುಕ್ಕುಂದಾ",
    panchayat_name_en: "KUKKUNDA",
    panchayat_code: "1515007004"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಸೆಡಂ",
    block_name_en: "SEDAM",
    block_code: "1515007",
    panchayat_name_kn: "ಕುರುಕುಂಟಾ",
    panchayat_name_en: "KURKUNTA",
    panchayat_code: "1515007013"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಸೆಡಂ",
    block_name_en: "SEDAM",
    block_code: "1515007",
    panchayat_name_kn: "ಲಿಂಗಂಪಲ್ಲಿ",
    panchayat_name_en: "LINGAMPALLI",
    panchayat_code: "1515007002"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಸೆಡಂ",
    block_name_en: "SEDAM",
    block_code: "1515007",
    panchayat_name_kn: "ಮದನಾ",
    panchayat_name_en: "MADANA",
    panchayat_code: "1515007020"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಸೆಡಂ",
    block_name_en: "SEDAM",
    block_code: "1515007",
    panchayat_name_kn: "ಮಳಖೇಡ",
    panchayat_name_en: "MALKHED",
    panchayat_code: "1515007011"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಸೆಡಂ",
    block_name_en: "SEDAM",
    block_code: "1515007",
    panchayat_name_kn: "ಮೇದಕ್‌",
    panchayat_name_en: "MEDAK",
    panchayat_code: "1515007007"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಸೆಡಂ",
    block_name_en: "SEDAM",
    block_code: "1515007",
    panchayat_name_kn: "ಮೋಘಾ (ಕೆ)",
    panchayat_name_en: "MOGHA+(K)",
    panchayat_code: "1515007005"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಸೆಡಂ",
    block_name_en: "SEDAM",
    block_code: "1515007",
    panchayat_name_kn: "ಮುದೋಳ",
    panchayat_name_en: "MUDOL",
    panchayat_code: "1515007010"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಸೆಡಂ",
    block_name_en: "SEDAM",
    block_code: "1515007",
    panchayat_name_kn: "ನೀಲಹಳ್ಳಿ",
    panchayat_name_en: "NEELHALLI",
    panchayat_code: "1515007018"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಸೆಡಂ",
    block_name_en: "SEDAM",
    block_code: "1515007",
    panchayat_name_kn: "ರಂಜೋಳ",
    panchayat_name_en: "RANJOL",
    panchayat_code: "1515007014"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಸೆಡಂ",
    block_name_en: "SEDAM",
    block_code: "1515007",
    panchayat_name_kn: "ರಿಬ್ಬನಪಲ್ಲಿ",
    panchayat_name_en: "RIBBANPALLI",
    panchayat_code: "1515007006"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಸೆಡಂ",
    block_name_en: "SEDAM",
    block_code: "1515007",
    panchayat_name_kn: "SINDANMADU",
    panchayat_name_en: "SINDANMADU",
    panchayat_code: "1515007026"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಸೆಡಂ",
    block_name_en: "SEDAM",
    block_code: "1515007",
    panchayat_name_kn: "ತೆಲಕೂರ",
    panchayat_name_en: "TELKUR",
    panchayat_code: "1515007017"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಸೆಡಂ",
    block_name_en: "SEDAM",
    block_code: "1515007",
    panchayat_name_kn: "ಊಡಗಿ",
    panchayat_name_en: "UOODAGI",
    panchayat_code: "1515007027"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಸೆಡಂ",
    block_name_en: "SEDAM",
    block_code: "1515007",
    panchayat_name_kn: "YADAGA",
    panchayat_name_en: "YADAGA",
    panchayat_code: "1515007027"
  },

  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಶಹಬಾದ್",
    block_name_en: "SHABAD",
    block_code: "1515013",
    panchayat_name_kn: "ಭಂಕೂರ",
    panchayat_name_en: "BHANKUR",
    panchayat_code: "1515004005"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಶಹಬಾದ್",
    block_name_en: "SHABAD",
    block_code: "1515013",
    panchayat_name_kn: "ಹೊನಗುಂಟಾ",
    panchayat_name_en: "HONAGUNTA",
    panchayat_code: "1515004014"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಶಹಬಾದ್",
    block_name_en: "SHABAD",
    block_code: "1515013",
    panchayat_name_kn: "ಮಾಲಗತ್ತಿ",
    panchayat_name_en: "MALGATTI",
    panchayat_code: "1515004025"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಶಹಬಾದ್",
    block_name_en: "SHABAD",
    block_code: "1515013",
    panchayat_name_kn: "ಮರತೂರ",
    panchayat_name_en: "MARATUR",
    panchayat_code: "1515004026"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಶಹಬಾದ್",
    block_name_en: "SHABAD",
    block_code: "1515013",
    panchayat_name_kn: "MUGALNAGAO",
    panchayat_name_en: "MUGALNAGAON",
    panchayat_code: "1515004039"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಶಹಬಾದ್",
    block_name_en: "SHABAD",
    block_code: "1515013",
    panchayat_name_kn: "ರಾವೂರ",
    panchayat_name_en: "RAVOOR",
    panchayat_code: "1515004030"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಶಹಬಾದ್",
    block_name_en: "SHABAD",
    block_code: "1515013",
    panchayat_name_kn: "ತೊನಸನಹಳ್ಳಿ(ಎಸ್)",
    panchayat_name_en: "TONASNHALLI(S)",
    panchayat_code: "1515004034"
  },

  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಯಡ್ರಾಮಿ",
    block_name_en: "YADRAMI",
    block_code: "1515014",
    panchayat_name_kn: "ಆಲೂರ",
    panchayat_name_en: "ALOOR",
    panchayat_code: "1515006019"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಯಾಡ್ರಮಿ",
    block_name_en: "YADRAMI",
    block_code: "1515014",
    panchayat_name_kn: "ಅರಳಗುಂಡಗಿ",
    panchayat_name_en: "ARALAGUNDAGI",
    panchayat_code: "1515006027"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಯಾಡ್ರಮಿ",
    block_name_en: "YADRAMI",
    block_code: "1515014",
    panchayat_name_kn: "ಬಳಬಟ್ಟಿ",
    panchayat_name_en: "BALBATTI",
    panchayat_code: "1515006017"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಯಾಡ್ರಮಿ",
    block_name_en: "YADRAMI",
    block_code: "1515014",
    panchayat_name_kn: "ಬಿಳವಾರ",
    panchayat_name_en: "BILWAR",
    panchayat_code: "1515006016"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಯಾಡ್ರಮಿ",
    block_name_en: "YADRAMI",
    block_code: "1515014",
    panchayat_name_kn: "ಇಜೇರಿ",
    panchayat_name_en: "IJERI",
    panchayat_code: "1515006014"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಯಾಡ್ರಮಿ",
    block_name_en: "YADRAMI",
    block_code: "1515014",
    panchayat_name_kn: "ಕಾಚಾಪೂರ",
    panchayat_name_en: "KACHAPUR",
    panchayat_code: "1515006038"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಯಾಡ್ರಮಿ",
    block_name_en: "YADRAMI",
    block_code: "1515014",
    panchayat_name_kn: "ಕಡಣಿ",
    panchayat_name_en: "KADKOL",
    panchayat_code: "1515006028"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಯಾಡ್ರಮಿ",
    block_name_en: "YADRAMI",
    block_code: "1515014",
    panchayat_name_kn: "ಕರಕಿಹಳ್ಳಿ",
    panchayat_name_en: "KARKIHALLI",
    panchayat_code: "1515006036"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಯಾಡ್ರಮಿ",
    block_name_en: "YADRAMI",
    block_code: "1515014",
    panchayat_name_kn: "ಕುಕನೂರ",
    panchayat_name_en: "KUKNUR",
    panchayat_code: "1515006021"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಯಾಡ್ರಮಿ",
    block_name_en: "YADRAMI",
    block_code: "1515014",
    panchayat_name_kn: "ಕುರಳಗೇರಾ",
    panchayat_name_en: "KURALGERA",
    panchayat_code: "1515006026"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಯಾಡ್ರಮಿ",
    block_name_en: "YADRAMI",
    block_code: "1515014",
    panchayat_name_kn: "ಮಾಗಣಗೇರಾ",
    panchayat_name_en: "MAGANGERA",
    panchayat_code: "1515006024"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಯಾಡ್ರಮಿ",
    block_name_en: "YADRAMI",
    block_code: "1515014",
    panchayat_name_kn: "ಮಳ್ಳಿ",
    panchayat_name_en: "MALLI",
    panchayat_code: "1515006023"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಯಾಡ್ರಮಿ",
    block_name_en: "YADRAMI",
    block_code: "1515014",
    panchayat_name_kn: "ಸಾಥಖೇಡ",
    panchayat_name_en: "SATHKHED",
    panchayat_code: "1515006035"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಯಾಡ್ರಮಿ",
    block_name_en: "YADRAMI",
    block_code: "1515014",
    panchayat_name_kn: "ಸುಂಬಡ",
    panchayat_name_en: "SUMBAD",
    panchayat_code: "1515006039"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಯಾಡ್ರಮಿ",
    block_name_en: "YADRAMI",
    block_code: "1515014",
    panchayat_name_kn: "ವಡಗೇರಾ",
    panchayat_name_en: "WADGERA",
    panchayat_code: "1515006025"
  },
  {
    district_name_kn: "ಕಲಬುರಗಿ",
    district_name_en: "KALABURAGI",
    district_code: "1515",
    block_name_kn: "ಯಾಡ್ರಮಿ",
    block_name_en: "YADRAMI",
    block_code: "1515014",
    panchayat_name_kn: "ಯಲಗೂಡ",
    panchayat_name_en: "YALAGOD",
    panchayat_code: "1515006018"
  }
];
